export {default as images} from "./logo2.1.png" 
export { default as cartoon } from "./cartoon1.5.png" 
export { default as html } from "./html.png" 
export { default as css } from "./css.png" 
export { default as javascript } from "./javascript.png" 
export { default as react } from "./react.png" 
export { default as sass } from "./sass.png" 
export { default as reactbs5 } from "./react-bs5.png"
export { default as fast } from "./fast.png"
export { default as responsive } from "./responsive.png"
export { default as blube } from "./blube.png"
export { default as dynamic } from "./dynamic.png"
export { default as profile } from "./profile.png"
export { default as pc } from "./pc.png"
export { default as vscode } from "./vscode.png"
export { default as bs5 } from "./bs5.png"
export { default as github } from "./github.png"
export { default as chatgpt } from "./chatgpt1.png"
